PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT ?entity ?type
WHERE {
  # Direct subclassing
  #?entity a ssn:SensingDevice .
  # Indirect subclassing (derived from many direct)
  ?entity rdf:type ?type .
  ?type rdfs:subClassOf* ssn:SensingDevice .
  # One liner
  #?entity  rdf:type/rdfs:subClassOf* ssn:SensingDevice .
}
